name: jule # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.9' # just for humans, typically '1.2+git' or '1.3.2'
summary: jule is a fun utility which makes text harder to read! # 79 char long summary
description: |
  No description yet, working on it ;)
title: Jumble Letters
website: https://github.com/IsakTheHacker/jumble-letters
source-code: https://github.com/IsakTheHacker/jumble-letters.git
issues: https://github.com/IsakTheHacker/jumble-letters/issues

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  jule:
    command: bin/jule

parts:
  jule:
    source: https://github.com/IsakTheHacker/jumble-letters.git
    source-type: git
    override-pull: snapcraftctl pull && mkdir -p bin
    plugin: make
    build-packages: []
