name: jule # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: jule is a fun utility which makes text harder to read! # 79 char long summary
description: |
  Jumble letters is a tool that mixes up every letter in a
  sentence except the first and last letters in each word
title: Jumble Letters
website: https://github.com/IsakTheHacker/jumble-letters
source-code: https://github.com/IsakTheHacker/jumble-letters.git
issues: https://github.com/IsakTheHacker/jumble-letters/issues

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: amd64

  - build-on: i386
    run-on: i386

	- build-on: arm64
    run-on: arm64

  - build-on: armhf
    run-on: armhf

  - build-on: s390x
    run-on: s390x

  - build-on: ppc64el
    run-on: ppc64el

apps:
  jule:
    command: bin/jule

parts:
  jule:
    source: https://github.com/IsakTheHacker/jumble-letters.git
    source-type: git
    override-pull: snapcraftctl pull && mkdir -p bin
    plugin: make
    build-packages: []
